In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import r2_score, mean_squared_error

In [4]:
df = pd.read_csv("auto-mpg (1).csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [5]:
df.shape

(398, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [7]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [8]:
df['horsepower'] = df['horsepower'].replace('?', np.nan)
df['horsepower']

0      130
1      165
2      150
3      150
4      140
      ...
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object

In [9]:
df['horsepower'] = df['horsepower'].astype(float)
df['horsepower']

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [10]:
df = df.dropna()
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,1,chevy s-10

In [12]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000

In [13]:
X = df.drop(columns=['mpg','car name'])
y = df['mpg']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
ridge = Ridge(alpha=1.0)
ridge.fit(X_train,y_train)

ridge_pred = ridge.predict(X_test)
ridge_pred

array([25.85868962, 26.08337294, 34.4325441 , 24.86163987, 28.44932672,
       30.54752428,  8.62163634, 30.70168468, 20.58472635, 28.648384  ,
       12.51607903, 25.32975287, 16.7640145 , 29.68056926, 21.95154501,
       29.23884069, 20.4458903 , 33.3535135 , 26.74655535, 29.95417505,
       18.9689014 , 34.38328208, 35.43380588, 14.90821876, 28.4852427 ,
       25.66826261, 21.12117242, 16.26409053, 28.63611837, 24.11747496,
       13.44023693, 23.42283436, 20.83371299, 31.87767912, 12.26216215,
       36.16366494, 11.04082072, 24.38475659, 11.55786546,  7.17042973,
       12.95754192, 27.59040145, 34.65828291, 26.45065072, 12.08670796,
        9.70833461, 17.61851167, 31.39617675, 24.30619623, 30.20760158,
       11.91229637, 26.51160642, 23.09662248, 35.05345906, 28.14654357,
       17.78487247, 20.29408544, 22.64157858, 22.74625464, 26.00889454,
        8.39981469, 22.65036931, 25.78429934, 23.45352295, 29.9328709 ,
       28.68935161, 25.76714381, 29.44056216, 21.74964331,  9.9689796 ,
       22.72809321, 13.24398177, 26.86320749, 28.00605072, 24.20093004,
       24.11599351, 14.01546485, 14.8474473 , 25.7881801 ])

In [18]:
print(ridge.score(X_test,y_test))

0.7890425833738295

In [19]:
print(ridge.coef_)

[-0.53605509  1.34475957 -0.84685405 -4.98299806  0.07001785  2.76196589
  1.2882827 ]

In [20]:
print("R2 Score:", r2_score(y_test,ridge_pred))
print("MSE:", mean_squared_error(y_test,ridge_pred))

R2 Score: 0.7890425833738295
MSE: 10.76738958337502

In [21]:
lasso = Lasso(alpha=0.1)
lasso.fit(X_train,y_train)

lasso_pred = lasso.predict(X_test)
lasso_pred

array([25.93518161, 26.41549402, 33.94141282, 25.12503848, 28.44865492,
       30.32352566,  8.51062345, 30.45936671, 20.57936671, 28.70455357,
       12.39442787, 25.63843975, 16.71806012, 29.49942498, 22.80972631,
       29.43181649, 20.72756931, 32.94187511, 26.97616747, 29.86990867,
       19.25013846, 33.8572043 , 35.03146734, 15.10576151, 28.67046266,
       25.96927071, 21.37349775, 16.53974823, 28.29224374, 24.08047163,
       13.47115116, 23.15288892, 21.25283092, 31.39878657, 11.79820292,
       35.72723537, 11.72134359, 24.79078267, 12.12699636,  7.8734792 ,
       13.33451425, 27.7689044 , 34.37539902, 26.67906029, 12.2447476 ,
        9.42810173, 17.46578748, 31.41438033, 24.13484481, 30.2448222 ,
       11.97706729, 26.43105902, 23.16338007, 34.53847021, 27.84692921,
       17.62717127, 20.60891125, 22.4227531 , 23.08985534, 25.96747529,
        8.11133628, 22.36228091, 26.3331748 , 23.69008878, 29.55669123,
       28.54838825, 25.85683249, 29.50811957, 22.03243672,  9.60288684,
       22.6232029 , 13.44427899, 27.15389684, 28.07741377, 24.03853633,
       24.58321231, 13.95327721, 15.21980673, 25.86190997])

In [22]:
print(lasso.score(X_test,y_test))

0.786303117409425

In [23]:
print(lasso.coef_)

[-0.         -0.         -0.52323423 -4.58724613  0.          2.67005547
  1.07821484]

In [24]:
print("R2 Score:", r2_score(y_test,lasso_pred))
print("MSE:", mean_squared_error(y_test,lasso_pred))

R2 Score: 0.786303117409425
MSE: 10.907213523963984